#!/bin/bash

# https://www.deepl.com/docs-api/translate-text/translate-text/
# https://github.com/DeepLcom/openapi/blob/main/openapi.yaml
# https://www.deepl.com/docs-api/api-access/openapi/
# https://www.deepl.com/pro-api/

if [ -z "$DEEPL_API_KEY" ]; then
    echo 'Please set $DEEPL_API_KEY to one from your account. It used to be under https://www.deepl.com/account/summary .
e.g. with:
$ export DEEPL_API_KEY="12434...."
'
    exit 1
fi

if [ $# -lt 2  -o $# -gt 3 ]; then
    echo '# Usage:

deepl SRC_LANG DST_LANG [TEXT OR STDIN]

# Examples:
deepl EN DE "This is test."
echo "This is test." | deepl EN DE
cat README.md | deepl EN DE

# For using API Pro endpoint
export DEEPL_API_PRO=pro
# Fur using custom endpoint
export DEEPL_API_ENDPOINT="http...."
'
exit 1
fi

srcl="$1"
dstl="$2"

if [ $# -eq 3 ]; then
    text="$3"  # for --data-urlencode
else
    text="$(cat)"  # for --data-urlencode
fi

if [ -z "$DEEPL_API_ENDPOINT" ]; then
    if [ -z "$DEEPL_API_PRO" ]; then
        DEEPL_API_ENDPOINT='https://api-free.deepl.com/v2/translate'
    else
        DEEPL_API_ENDPOINT='https://api.deepl.com/v2/translate'
    fi
fi

# set -x #for debugging, also you may want to consider to comment "#| jq.."

curl --silent -X POST "${DEEPL_API_ENDPOINT}" \
    -H "Authorization: DeepL-Auth-Key ${DEEPL_API_KEY}" \
	--data-urlencode "text=${text}" \
	-d "source_lang=${srcl}" \
	-d "target_lang=${dstl}" | jq -r '.translations[0].text'
